'use strict';
const alumni=[
{id:'mariana',name:'Mariana Torres',year:'2017',city:'Tampa, Florida, USA',region:'North America',industry:'Marketing',role:'Marketing Manager',employer:'BrightWave Media',lat:27.95,lng:-82.46,tags:['Marketing','Leadership','Mentoring'],quote:'The alumni community helped turn introductions into lasting professional relationships.',photo:'assets/profiles/mariana.jpg',highlighted:true},
{id:'jamal',name:'Jamal Carter',year:'2012',city:'Atlanta, Georgia, USA',region:'North America',industry:'Finance',role:'Senior Project Manager',employer:'Metro Capital',lat:33.75,lng:-84.39,tags:['Finance','Leadership'],quote:'Different paths, shared purpose.',photo:'assets/profiles/jamal.jpg',highlighted:true},
{id:'emily',name:'Emily Rhodes',year:'2015',city:'London, United Kingdom',region:'Europe',industry:'Healthcare',role:'Clinical Operations Lead',employer:'Northbridge Health',lat:51.51,lng:-.13,tags:['Healthcare','Service'],quote:'Service shaped my leadership.',photo:'assets/profiles/emily.jpg',highlighted:false},
{id:'daniel',name:'Daniel Kim',year:'2018',city:'Seoul, South Korea',region:'Asia Pacific',industry:'Technology',role:'Cybersecurity Analyst',employer:'Nimbus Systems',lat:37.57,lng:126.98,tags:['Technology','Analytics'],quote:'A global education opened new doors.',photo:'assets/profiles/daniel.jpg',highlighted:true},
{id:'sofia',name:'Sofia Martinez',year:'2014',city:'Madrid, Spain',region:'Europe',industry:'Education',role:'International Program Director',employer:'Global Learning Alliance',lat:40.42,lng:-3.7,tags:['Education','Global'],quote:'Community travels with every alumnus.',photo:'assets/profiles/sofia.jpg',highlighted:false},
{id:'liam',name:'Liam O’Connor',year:'2010',city:'Sydney, Australia',region:'Asia Pacific',industry:'Operations',role:'Operations Director',employer:'Pacific Logistics',lat:-33.87,lng:151.21,tags:['Operations','Leadership'],quote:'Purpose keeps teams moving forward.',photo:'assets/profiles/liam.jpg',highlighted:false}
];
const regionAnchors=[{name:'NORTH AMERICA',lat:44,lng:-103},{name:'SOUTH AMERICA',lat:-18,lng:-59},{name:'EUROPE',lat:51,lng:18},{name:'AFRICA',lat:3,lng:21},{name:'ASIA',lat:39,lng:99},{name:'AUSTRALIA',lat:-26,lng:134}];
const map=L.map('map',{zoomControl:false,worldCopyJump:true,minZoom:2,zoomSnap:.25}).setView([17,5],2.15);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const regionLayer=L.layerGroup().addTo(map);regionAnchors.forEach(r=>L.marker([r.lat,r.lng],{interactive:false,icon:L.divIcon({className:'region-map-label',html:r.name,iconSize:[140,24],iconAnchor:[70,12]})}).addTo(regionLayer));
const markerLayer=L.layerGroup().addTo(map);const markerRecords=[];
function markerIcon(isHighlighted){return L.divIcon({className:'',html:`<span style="display:block;width:${isHighlighted?16:12}px;height:${isHighlighted?16:12}px;border-radius:50%;background:#f7bd2d;border:${isHighlighted?3:2}px solid #fff3bd;box-shadow:0 0 ${isHighlighted?16:9}px #ffd03c"></span>`,iconSize:[16,16],iconAnchor:[8,8]})}
alumni.forEach(a=>{const marker=L.marker([a.lat,a.lng],{icon:markerIcon(a.highlighted),alt:`${a.name}, ${a.city}`}).bindTooltip(`${a.name} · ${a.industry}`,{direction:'top'}).on('click',()=>selectProfile(a,true));marker.addTo(markerLayer);markerRecords.push({a,marker})});
const clusterData=[{lat:39,lng:-98,count:'12.4K'},{lat:50,lng:10,count:'4.7K'},{lat:34,lng:110,count:'1.9K'},{lat:-7,lng:23,count:'610'},{lat:-24,lng:135,count:'430'},{lat:-18,lng:-61,count:'320'}];clusterData.forEach(c=>L.marker([c.lat,c.lng],{interactive:false,icon:L.divIcon({className:'',html:`<span style="display:grid;place-items:center;width:44px;height:44px;border-radius:50%;background:#08744e;color:#fff;border:2px solid #f7bd2d;font:700 12px 'DM Sans';box-shadow:0 0 15px #00251f">${c.count}</span>`,iconSize:[44,44],iconAnchor:[22,22]})}).addTo(map));
const searchInput=document.getElementById('searchInput'),industryFilter=document.getElementById('industryFilter'),yearFilter=document.getElementById('yearFilter'),regionFilter=document.getElementById('regionFilter'),profileCard=document.getElementById('profileCard'),featuredGrid=document.getElementById('featuredGrid'),resultCount=document.getElementById('resultCount');
const unique=(key)=>[...new Set(alumni.map(a=>a[key]))].sort();unique('industry').forEach(v=>industryFilter.add(new Option(v,v)));unique('year').forEach(v=>yearFilter.add(new Option(v,v)));unique('region').forEach(v=>regionFilter.add(new Option(v,v)));
function selectProfile(a,move){profileCard.className=`profile-card ${a.highlighted?'highlighted':''}`;profileCard.innerHTML=`${a.highlighted?'<span class="ribbon">★ HIGHLIGHTED PROFILE</span>':''}<div class="profile-head"><img class="profile-photo" src="${a.photo}" alt="Fictional profile portrait for ${a.name}"><div><h2>${a.name} ’${a.year.slice(-2)}</h2><p>${a.city}<br><strong>${a.role}</strong><br>${a.employer}</p><a class="profile-link" href="#">View profile ↗</a></div></div><p class="quote">“${a.quote}”</p><div class="tags">${a.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="connect">Connect with ${a.name.split(' ')[0]}</button>`;profileCard.querySelector('.profile-link').addEventListener('click',e=>{e.preventDefault();alert('Demonstration profile only.')});profileCard.querySelector('.connect').addEventListener('click',()=>alert('Connection workflow placeholder.'));if(move)map.flyTo([a.lat,a.lng],5,{duration:.8})}
function renderFeatured(filterSet=alumni){featuredGrid.innerHTML=filterSet.map(a=>`<article class="featured-card ${a.highlighted?'highlighted':''}" data-id="${a.id}" tabindex="0"><img src="${a.photo}" alt="Fictional profile portrait for ${a.name}"><div class="featured-content">${a.highlighted?'<span class="featured-badge">★ HIGHLIGHTED</span>':''}<h3>${a.name} ’${a.year.slice(-2)}</h3><p class="meta">${a.city}</p><p class="role">${a.role}<br>${a.employer}</p><a href="#">View profile ↗</a></div></article>`).join('');featuredGrid.querySelectorAll('.featured-card').forEach(card=>{const activate=()=>{const a=alumni.find(x=>x.id===card.dataset.id);selectProfile(a,true);document.getElementById('explore').scrollIntoView({behavior:'smooth'})};card.addEventListener('click',e=>{if(e.target.tagName==='A')e.preventDefault();activate()});card.addEventListener('keydown',e=>{if(e.key==='Enter')activate()})})}
function currentMatches(){const q=searchInput.value.trim().toLowerCase();return alumni.filter(a=>{const text=[a.name,a.city,a.region,a.industry,a.role,a.employer].join(' ').toLowerCase();return(!q||text.includes(q))&&(industryFilter.value==='all'||a.industry===industryFilter.value)&&(yearFilter.value==='all'||a.year===yearFilter.value)&&(regionFilter.value==='all'||a.region===regionFilter.value)})}
function applyFilters(){const matches=currentMatches();markerLayer.clearLayers();markerRecords.forEach(({a,marker})=>{if(matches.includes(a))marker.addTo(markerLayer)});resultCount.textContent=`${matches.length} profile${matches.length===1?'':'s'} shown`;renderFeatured(matches);if(matches.length===1){map.flyTo([matches[0].lat,matches[0].lng],5,{duration:.7});selectProfile(matches[0],false)}else if(matches.length>1){map.fitBounds(L.latLngBounds(matches.map(a=>[a.lat,a.lng])),{padding:[55,55],maxZoom:4.25,animate:true})}else{profileCard.className='profile-card';profileCard.innerHTML='<h2>No profiles found</h2><p>Adjust the search or filters to see other fictional alumni.</p>';map.setView([17,5],2.15)}}
[searchInput,industryFilter,yearFilter,regionFilter].forEach(el=>el.addEventListener(el===searchInput?'input':'change',applyFilters));document.getElementById('resetButton').addEventListener('click',()=>{searchInput.value='';industryFilter.value=yearFilter.value=regionFilter.value='all';markerLayer.clearLayers();markerRecords.forEach(({marker})=>marker.addTo(markerLayer));resultCount.textContent='6 profiles shown';renderFeatured(alumni);selectProfile(alumni[0],false);map.setView([17,5],2.15)});document.getElementById('showAllFeatured').addEventListener('click',()=>{searchInput.value='';industryFilter.value=yearFilter.value=regionFilter.value='all';applyFilters();document.getElementById('featured').scrollIntoView({behavior:'smooth'})});
selectProfile(alumni[0],false);renderFeatured(alumni);
const dialog=document.getElementById('joinDialog');document.getElementById('joinButton').addEventListener('click',()=>dialog.showModal());document.getElementById('closeDialog').addEventListener('click',()=>dialog.close());document.querySelectorAll('.form-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.form-tab,.form-pane').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.pane).classList.add('active')}));document.getElementById('joinForm').addEventListener('submit',e=>{e.preventDefault();alert('Submitted for authorization review. Nothing has been published.');dialog.close()});
