const alumni=[
{name:'Mariana Torres',year:'2017',city:'Tampa, Florida, USA',region:'North America',industry:'Marketing',role:'Marketing Manager',employer:'BrightWave Media',lat:27.95,lng:-82.46,tags:['Marketing','Leadership','Mentoring'],quote:'The alumni community helped turn introductions into lasting professional relationships.',photo:'assets/profiles/mariana.jpg',highlighted:true},
{name:'Jamal Carter',year:'2012',city:'Atlanta, Georgia, USA',region:'North America',industry:'Finance',role:'Senior Project Manager',employer:'Metro Capital',lat:33.75,lng:-84.39,tags:['Finance','Leadership'],quote:'Different paths, shared purpose.',photo:'assets/profiles/jamal.jpg',highlighted:true},
{name:'Emily Rhodes',year:'2015',city:'London, UK',region:'Europe',industry:'Healthcare',role:'Clinical Operations Lead',employer:'Northbridge Health',lat:51.51,lng:-.13,tags:['Healthcare','Service'],quote:'Service shaped my leadership.',photo:'assets/profiles/emily.jpg',highlighted:false},
{name:'Daniel Kim',year:'2018',city:'Seoul, South Korea',region:'Asia Pacific',industry:'Technology',role:'Cybersecurity Analyst',employer:'Nimbus Systems',lat:37.57,lng:126.98,tags:['Technology','Analytics'],quote:'A global education opened new doors.',photo:'assets/profiles/daniel.jpg',highlighted:true},
{name:'Sofia Martinez',year:'2014',city:'Madrid, Spain',region:'Europe',industry:'Education',role:'International Program Director',employer:'Global Learning Alliance',lat:40.42,lng:-3.7,tags:['Education','Global'],quote:'Community travels with every alumnus.',photo:'assets/profiles/sofia.jpg',highlighted:false},
{name:'Liam O’Connor',year:'2010',city:'Sydney, Australia',region:'Asia Pacific',industry:'Operations',role:'Operations Director',employer:'Pacific Logistics',lat:-33.87,lng:151.21,tags:['Operations','Leadership'],quote:'Purpose keeps teams moving forward.',photo:'assets/profiles/liam.jpg',highlighted:false}
];
const map=L.map('map',{zoomControl:false,worldCopyJump:true,minZoom:2}).setView([18,7],2);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const icon=L.divIcon({className:'',html:'<span class="featured-map-marker" style="display:block;width:13px;height:13px;border-radius:50%;background:#ffc12b;border:2px solid #fff0b4"></span>',iconSize:[11,11],iconAnchor:[5,5]});const layers=[];let selected=alumni[0];
function initials(n){return n.split(' ').map(x=>x[0]).join('').slice(0,2)}
function profile(a){selected=a;document.getElementById('selectedProfile').className=`selected-profile ${a.highlighted?'highlighted':''}`;document.getElementById('selectedProfile').innerHTML=`${a.highlighted?'<div class="highlight-ribbon">★ HIGHLIGHTED PROFILE</div>':''}<div class="profile-head"><img class="profile-photo" src="${a.photo}" alt="Fictional profile portrait for ${a.name}"><div><h2>${a.name} ’${a.year.slice(-2)}</h2><p>${a.city}<br><strong>${a.role}</strong><br>at ${a.employer}</p><a class="li-link" href="#">▣　View LinkedIn Profile ↗</a></div></div><p class="testimonial">“${a.quote}”</p><div class="tags">${a.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="connect">➤　Connect with ${a.name.split(' ')[0]}</button><a class="more" href="#">View more alumni in ${a.city.split(',')[0]}　→</a>`;document.querySelectorAll('.li-link,.more').forEach(x=>x.onclick=e=>{e.preventDefault();alert('Demonstration profile only. Add a verified link after authorization.')});document.querySelector('.connect').onclick=()=>alert('Connection workflow placeholder.');}
profile(selected);[...new Set(alumni.map(a=>a.industry))].sort().forEach(v=>industry.add(new Option(v,v)));[...new Set(alumni.map(a=>a.year))].sort().forEach(v=>year.add(new Option(v,v)));[...new Set(alumni.map(a=>a.region))].sort().forEach(v=>location.add(new Option(v,v)));
alumni.forEach(a=>{const m=L.marker([a.lat,a.lng],{icon,alt:`${a.name}, ${a.city}`}).addTo(map).bindTooltip(`${a.name} · ${a.industry}`);m.on('click',()=>profile(a));layers.push({a,m})});
const clusters=[{lat:39,lng:-98,n:'12.4K'},{lat:50,lng:10,n:'4.7K'},{lat:34,lng:110,n:'1.9K'},{lat:4,lng:22,n:'610'},{lat:-23,lng:133,n:'430'},{lat:-15,lng:-60,n:'320'}];clusters.forEach(c=>L.marker([c.lat,c.lng],{icon:L.divIcon({className:'',html:`<span style="display:grid;place-items:center;width:48px;height:48px;border-radius:50%;background:#087349;color:white;border:2px solid #ffd23d;font:700 13px Inter;box-shadow:0 0 20px #001">${c.n}</span>`,iconSize:[48,48],iconAnchor:[24,24]})}).addTo(map));
function filter(){const q=search.value.toLowerCase();layers.forEach(({a,m})=>{const h=[a.name,a.city,a.industry,a.role,a.employer].join(' ').toLowerCase();const show=(!q||h.includes(q))&&(industry.value==='all'||a.industry===industry.value)&&(year.value==='all'||a.year===year.value)&&(location.value==='all'||a.region===location.value);if(show&&!map.hasLayer(m))m.addTo(map);if(!show&&map.hasLayer(m))map.removeLayer(m)})}[search,industry,year,location].forEach(x=>x.addEventListener(x.tagName==='INPUT'?'input':'change',filter));
function cards(){alumniStrip.innerHTML=alumni.slice(0,5).map(a=>`<article class="alumni-card ${a.highlighted?'highlighted':''}"><img class="mini-photo" src="${a.photo}" alt="Fictional profile portrait for ${a.name}"><div><h3>${a.name} ’${a.year.slice(-2)}</h3><p>${a.city}<br>${a.role}<br>at ${a.employer}</p><a href="#">▣　View on LinkedIn ↗</a></div></article>`).join('');alumniStrip.querySelectorAll('a').forEach(x=>x.onclick=e=>{e.preventDefault();alert('Demonstration profile only.')})}cards();
viewAll.onclick=()=>alert('All-alumni directory view placeholder.');prev.onclick=()=>alumniStrip.scrollBy({left:-300,behavior:'smooth'});next.onclick=()=>alumniStrip.scrollBy({left:300,behavior:'smooth'});joinBtn.onclick=()=>join.showModal();closeDialog.onclick=()=>join.close();document.querySelectorAll('.form-tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.form-tab,.form-pane').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.pane).classList.add('active')});joinForm.onsubmit=e=>{e.preventDefault();alert('Submitted for authorization review. Nothing has been published.');join.close()};
