const alumni=[
{name:'Jordan Carter',year:'2012',city:'Atlanta, Georgia',industry:'Finance',role:'Senior Portfolio Analyst',employer:'Southeastern Capital',lat:33.749,lng:-84.388,initials:'JC'},
{name:'Emily Rhodes',year:'2015',city:'London, United Kingdom',industry:'Healthcare',role:'Clinical Operations Lead',employer:'Global Health Partners',lat:51.507,lng:-.128,initials:'ER'},
{name:'Daniel Kim',year:'2018',city:'Seoul, South Korea',industry:'Technology',role:'Cybersecurity Analyst',employer:'Digital Trust Labs',lat:37.566,lng:126.978,initials:'DK'},
{name:'Sofia Martinez',year:'2014',city:'Madrid, Spain',industry:'Education',role:'International Programs Director',employer:'Global Learning Alliance',lat:40.416,lng:-3.704,initials:'SM'},
{name:'Liam O’Connor',year:'2010',city:'Sydney, Australia',industry:'Operations',role:'Operations Director',employer:'Pacific Logistics',lat:-33.868,lng:151.209,initials:'LO'},
{name:'Avery Brooks',year:'2020',city:'Tampa, Florida',industry:'Finance',role:'Commercial Banking Associate',employer:'Bay Financial Group',lat:27.951,lng:-82.457,initials:'AB'}];
const map=L.map('map',{zoomControl:false}).setView([25,-15],2);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
  maxZoom: 19,
  attribution: '&copy; OpenStreetMap contributors'
}).addTo(map);
const goldIcon=L.divIcon({className:'',html:'<div style="width:18px;height:18px;background:#f5bd32;border:3px solid #fff;border-radius:50%;box-shadow:0 2px 10px #0008"></div>',iconSize:[18,18]});
const profile=document.getElementById('profile');function show(a){profile.innerHTML=`<div class="person"><div class="avatar">${a.initials}</div><p class="eyebrow">AUTHORIZED ALUMNI PROFILE</p><h2>${a.name} ’${a.year.slice(-2)}</h2><p class="location">${a.city}</p><h4>${a.role}</h4><p>${a.employer}</p><span class="pill">${a.industry}</span><span class="pill">Open to connect</span><a class="linkedin" href="#" onclick="alert('Demo only: a verified LinkedIn URL would open here.');return false">View LinkedIn profile ↗</a><div class="consent"><b>Consent verified</b><br>Profile publication authorized by the alumnus. City-level location only.</div></div>`}
alumni.forEach(a=>L.marker([a.lat,a.lng],{icon:goldIcon}).addTo(map).bindTooltip(`${a.name} · ${a.industry}`).on('click',()=>show(a)));
const industries=[...new Set(alumni.map(a=>a.industry))];industries.forEach(x=>document.getElementById('industry').insertAdjacentHTML('beforeend',`<option>${x}</option>`));document.getElementById('cards').innerHTML=alumni.slice(0,3).map(a=>`<div class="card"><b>${a.name} ’${a.year.slice(-2)}</b><span>${a.role}<br>${a.city}</span></div>`).join('');
const modal=document.getElementById('modal');document.getElementById('joinBtn').onclick=()=>modal.classList.add('show');document.getElementById('close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.pane').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById(t.dataset.pane).classList.add('active')});document.getElementById('form').onsubmit=e=>{e.preventDefault();alert('Prototype: submission captured for review. No profile has been published.');modal.classList.remove('show')};
