const alumni=[
{name:'Jordan Carter',year:'2012',city:'Atlanta, Georgia',region:'North America',industry:'Finance',role:'Senior Portfolio Analyst',employer:'Southeastern Capital',lat:33.749,lng:-84.388,linkedin:'#'},
{name:'Emily Rhodes',year:'2015',city:'London, United Kingdom',region:'Europe',industry:'Healthcare',role:'Clinical Operations Lead',employer:'Global Health Partners',lat:51.507,lng:-.128,linkedin:'#'},
{name:'Daniel Kim',year:'2018',city:'Seoul, South Korea',region:'Asia Pacific',industry:'Technology',role:'Cybersecurity Analyst',employer:'Digital Trust Labs',lat:37.566,lng:126.978,linkedin:'#'},
{name:'Sofia Martinez',year:'2014',city:'Madrid, Spain',region:'Europe',industry:'Education',role:'International Programs Director',employer:'Global Learning Alliance',lat:40.416,lng:-3.704,linkedin:'#'},
{name:'Liam O’Connor',year:'2010',city:'Sydney, Australia',region:'Asia Pacific',industry:'Operations',role:'Operations Director',employer:'Pacific Logistics',lat:-33.868,lng:151.209,linkedin:'#'},
{name:'Avery Brooks',year:'2020',city:'Tampa, Florida',region:'North America',industry:'Finance',role:'Commercial Banking Associate',employer:'Bay Financial Group',lat:27.951,lng:-82.457,linkedin:'#'}];
const map=L.map('map',{zoomControl:false,worldCopyJump:true}).setView([24,-15],2);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const markerIcon=L.divIcon({className:'alumni-div-icon',html:'<span style="display:block;width:18px;height:18px;background:#f6bd32;border:3px solid #fff;border-radius:50%;box-shadow:0 2px 9px rgba(0,0,0,.55)"></span>',iconSize:[18,18],iconAnchor:[9,9]});
const layers=[];const profilePanel=document.getElementById('profilePanel');const industrySelect=document.getElementById('industry');const searchInput=document.getElementById('search');
[...new Set(alumni.map(a=>a.industry))].sort().forEach(value=>industrySelect.add(new Option(value,value)));
function initials(name){return name.split(' ').map(part=>part[0]).join('').replace('’','').slice(0,2)}
function openProfile(a){profilePanel.innerHTML=`<article class="profile-card"><div class="avatar">${initials(a.name)}</div><p class="profile-label">AUTHORIZED ALUMNI PROFILE</p><h2>${a.name} ’${a.year.slice(-2)}</h2><p class="location">${a.city}</p><h3>${a.role}</h3><p class="employer">${a.employer}</p><span class="pill">${a.industry}</span><span class="pill">${a.region}</span><a class="linkedin-btn" href="#" aria-label="Demonstration LinkedIn link for ${a.name}">View LinkedIn profile ↗</a><div class="verified"><strong>Consent verified</strong><br>Profile publication authorized by the alumnus. City-level location only.</div></article>`;profilePanel.querySelector('.linkedin-btn').addEventListener('click',e=>{e.preventDefault();alert('Demonstration profile only. Replace this link after authorization is verified.')})}
alumni.forEach(a=>{const marker=L.marker([a.lat,a.lng],{icon:markerIcon,alt:`${a.name}, ${a.city}`}).bindTooltip(`${a.name} · ${a.industry}`);marker.on('click',()=>openProfile(a));marker.bindPopup(`<strong>${a.name}</strong><br>${a.role}<br>${a.city}`);layers.push({record:a,marker});marker.addTo(map)});
function refresh(){const q=searchInput.value.trim().toLowerCase();const industry=industrySelect.value;let visible=0;layers.forEach(({record,marker})=>{const hay=[record.name,record.city,record.employer,record.role,record.industry].join(' ').toLowerCase();const show=(!q||hay.includes(q))&&(industry==='all'||record.industry===industry);if(show&&!map.hasLayer(marker))marker.addTo(map);if(!show&&map.hasLayer(marker))map.removeLayer(marker);if(show)visible++});document.getElementById('visibleCount').textContent=`${visible} profile${visible===1?'':'s'} shown`}
searchInput.addEventListener('input',refresh);industrySelect.addEventListener('change',refresh);document.getElementById('resetBtn').addEventListener('click',()=>{searchInput.value='';industrySelect.value='all';refresh();map.setView([24,-15],2)});
document.getElementById('cards').innerHTML=alumni.slice(0,3).map(a=>`<article class="card"><div class="card-top"><span class="mini-avatar">${initials(a.name)}</span><div><strong>${a.name} ’${a.year.slice(-2)}</strong><small>${a.city}</small></div></div><p>${a.role} at ${a.employer}</p></article>`).join('');
const dialog=document.getElementById('joinDialog');document.getElementById('joinBtn').addEventListener('click',()=>dialog.showModal());document.getElementById('closeDialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab,.pane').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.pane).classList.add('active')}));document.getElementById('joinForm').addEventListener('submit',e=>{e.preventDefault();alert('Prototype submission received for review. No profile has been published.');dialog.close()});
