'use strict';
const alumni=[
{id:'mariana',name:'Mariana Torres',year:'2017',city:'Tampa, Florida, USA',industry:'Marketing',region:'North America',role:'Marketing Manager',employer:'Google',quote:'Proud to be a Lion! Saint Leo gave me the foundation to lead with purpose.',tags:['Marketing','Leadership','Higher Education'],photo:'assets/profiles/mariana.jpg',point:[27.95,-82.46]},
{id:'jamal',name:'Jamal Carter',year:'2012',city:'Atlanta, Georgia, USA',industry:'Finance',region:'North America',role:'Senior Project Manager',employer:'Delta Air Lines',quote:'Different paths. Same purpose.',tags:['Finance','Leadership'],photo:'assets/profiles/jamal.jpg',point:[33.75,-84.39]},
{id:'emily',name:'Emily Rhodes',year:'2015',city:'London, UK',industry:'Healthcare',region:'Europe',role:'Clinical Nurse Specialist',employer:'NHS',quote:'Service shaped my leadership.',tags:['Healthcare','Service'],photo:'assets/profiles/emily.jpg',point:[51.51,-.13]},
{id:'daniel',name:'Daniel Kim',year:'2018',city:'Seoul, South Korea',industry:'Technology',region:'Asia Pacific',role:'Cybersecurity Analyst',employer:'Microsoft',quote:'A global education opened new doors.',tags:['Technology','Analytics'],photo:'assets/profiles/daniel.jpg',point:[37.57,126.98]},
{id:'sofia',name:'Sofia Martinez',year:'2014',city:'Madrid, Spain',industry:'Education',region:'Europe',role:'International Educator',employer:'Global Learning Alliance',quote:'Community travels with every Lion.',tags:['Education','Global'],photo:'assets/profiles/sofia.jpg',point:[40.42,-3.7]},
{id:'liam',name:'Liam O’Connor',year:'2010',city:'Sydney, Australia',industry:'Operations',region:'Asia Pacific',role:'Operations Director',employer:'Qantas',quote:'Purpose keeps teams moving forward.',tags:['Operations','Leadership'],photo:'assets/profiles/liam.jpg',point:[-33.87,151.21]}
];
const map=L.map('map',{crs:L.CRS.EPSG3857,zoomControl:false,attributionControl:false,minZoom:2,maxZoom:6,zoomSnap:.25,worldCopyJump:false}).setView([18,1],2.15);L.control.zoom({position:'bottomright'}).addTo(map);const imageBounds=L.latLngBounds([[-58,-180],[84,180]]);L.imageOverlay('assets/brand/world-map-mockup.jpg',imageBounds,{interactive:false,opacity:1}).addTo(map);map.setMaxBounds(imageBounds.pad(.15));
const hitLayer=L.layerGroup().addTo(map);const hits=[];function hitIcon(){return L.divIcon({className:'',html:'<span style="display:block;width:26px;height:26px;border-radius:50%;background:transparent"></span>',iconSize:[26,26],iconAnchor:[13,13]})}alumni.forEach(a=>{const marker=L.marker(a.point,{icon:hitIcon(),alt:`${a.name}, ${a.city}`}).bindTooltip(`${a.name} · ${a.industry}`,{direction:'top'}).on('click',()=>showProfile(a,true));marker.addTo(hitLayer);hits.push({a,marker})});let focusMarker=null;
const searchInput=document.getElementById('searchInput'),industryFilter=document.getElementById('industryFilter'),yearFilter=document.getElementById('yearFilter'),regionFilter=document.getElementById('regionFilter'),profileCard=document.getElementById('profileCard'),featuredTrack=document.getElementById('featuredTrack'),profileCount=document.getElementById('profileCount');const unique=k=>[...new Set(alumni.map(a=>a[k]))].sort();unique('industry').forEach(v=>industryFilter.add(new Option(v,v)));unique('year').forEach(v=>yearFilter.add(new Option(v,v)));unique('region').forEach(v=>regionFilter.add(new Option(v,v)));
function showProfile(a,move){profileCard.className='profile-card highlighted';profileCard.innerHTML=`<div class="profile-head"><img class="profile-photo" src="${a.photo}" alt="Fictional portrait for ${a.name}"><div><h3>${a.name} ’${a.year.slice(-2)}</h3><p>${a.city}<br><strong>${a.role}</strong><br>at ${a.employer}</p><a class="linkedin" href="#">▣　View LinkedIn Profile ↗</a></div></div><p class="profile-quote">“${a.quote}”</p><div class="tags">${a.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="connect-button">➤　Connect with ${a.name.split(' ')[0]}</button><a class="local-link" href="#">View more alumni in ${a.city.split(',')[0]}　→</a>`;profileCard.querySelectorAll('a').forEach(link=>link.onclick=e=>{e.preventDefault();alert('Demonstration profile only.')});profileCard.querySelector('.connect-button').onclick=()=>alert('Connection workflow placeholder.');if(focusMarker)map.removeLayer(focusMarker);focusMarker=L.marker(a.point,{interactive:false,icon:L.divIcon({className:'focus-marker',iconSize:[32,32],iconAnchor:[16,16]})}).addTo(map);if(move)map.flyTo(a.point,4,{duration:.8})}
function renderFeatured(records){featuredTrack.innerHTML=records.slice(0,5).map(a=>`<article class="featured-card" data-id="${a.id}" tabindex="0"><img src="${a.photo}" alt="Fictional portrait for ${a.name}"><div class="featured-copy"><h3>${a.name} ’${a.year.slice(-2)}</h3><p>${a.city}<br>${a.role}<br>at ${a.employer}</p><a href="#">▣　View on LinkedIn ↗</a></div></article>`).join('');featuredTrack.querySelectorAll('.featured-card').forEach(card=>{const open=()=>{const a=alumni.find(x=>x.id===card.dataset.id);showProfile(a,true);document.getElementById('mapExperience').scrollIntoView({behavior:'smooth'})};card.onclick=e=>{if(e.target.tagName==='A')e.preventDefault();open()};card.onkeydown=e=>{if(e.key==='Enter')open()}})}
function currentMatches(){const q=searchInput.value.trim().toLowerCase();return alumni.filter(a=>{const text=[a.name,a.city,a.industry,a.region,a.role,a.employer].join(' ').toLowerCase();return(!q||text.includes(q))&&(industryFilter.value==='all'||a.industry===industryFilter.value)&&(yearFilter.value==='all'||a.year===yearFilter.value)&&(regionFilter.value==='all'||a.region===regionFilter.value)})}
function applyFilters(){const matches=currentMatches();hitLayer.clearLayers();hits.forEach(({a,marker})=>{if(matches.includes(a))marker.addTo(hitLayer)});profileCount.textContent=`${matches.length} visible profile${matches.length===1?'':'s'}`;renderFeatured(matches);if(matches.length===1){showProfile(matches[0],true)}else if(matches.length>1){map.fitBounds(L.latLngBounds(matches.map(a=>a.point)),{padding:[60,60],maxZoom:3.6,animate:true})}else{profileCard.innerHTML='<h3>No profiles found</h3><p>Adjust the search or filters.</p>';map.setView([18,1],2.15)}}
[searchInput,industryFilter,yearFilter,regionFilter].forEach(el=>el.addEventListener(el===searchInput?'input':'change',applyFilters));document.getElementById('viewAllButton').onclick=()=>{searchInput.value='';industryFilter.value=yearFilter.value=regionFilter.value='all';applyFilters();map.setView([18,1],2.15)};document.getElementById('previousButton').onclick=()=>featuredTrack.scrollBy({left:-350,behavior:'smooth'});document.getElementById('nextButton').onclick=()=>featuredTrack.scrollBy({left:350,behavior:'smooth'});
showProfile(alumni[0],false);renderFeatured(alumni);
const dialog=document.getElementById('joinDialog');document.getElementById('joinButton').onclick=()=>dialog.showModal();document.getElementById('closeDialog').onclick=()=>dialog.close();document.querySelectorAll('.dialog-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.dialog-tab,.form-pane').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.pane).classList.add('active')});document.getElementById('joinForm').onsubmit=e=>{e.preventDefault();alert('Submitted for authorization review. Nothing has been published.');dialog.close()};
