'use strict';
const alumni=[
{id:'mariana',name:'Mariana Torres',year:'2017',city:'Tampa, Florida, USA',region:'North America',industry:'Marketing',role:'Marketing Manager',employer:'BrightWave Media',lat:27.95,lng:-82.46,tags:['Marketing','Leadership','Mentoring'],quote:'The alumni community helped turn introductions into lasting professional relationships.',photo:'assets/profiles/mariana.jpg',highlighted:true},
{id:'jamal',name:'Jamal Carter',year:'2012',city:'Atlanta, Georgia, USA',region:'North America',industry:'Finance',role:'Senior Project Manager',employer:'Metro Capital',lat:33.75,lng:-84.39,tags:['Finance','Leadership'],quote:'Different paths, shared purpose.',photo:'assets/profiles/jamal.jpg',highlighted:true},
{id:'emily',name:'Emily Rhodes',year:'2015',city:'London, United Kingdom',region:'Europe',industry:'Healthcare',role:'Clinical Operations Lead',employer:'Northbridge Health',lat:51.51,lng:-.13,tags:['Healthcare','Service'],quote:'Service shaped my leadership.',photo:'assets/profiles/emily.jpg',highlighted:false},
{id:'daniel',name:'Daniel Kim',year:'2018',city:'Seoul, South Korea',region:'Asia Pacific',industry:'Technology',role:'Cybersecurity Analyst',employer:'Nimbus Systems',lat:37.57,lng:126.98,tags:['Technology','Analytics'],quote:'A global education opened new doors.',photo:'assets/profiles/daniel.jpg',highlighted:true},
{id:'sofia',name:'Sofia Martinez',year:'2014',city:'Madrid, Spain',region:'Europe',industry:'Education',role:'International Program Director',employer:'Global Learning Alliance',lat:40.42,lng:-3.7,tags:['Education','Global'],quote:'Community travels with every alumnus.',photo:'assets/profiles/sofia.jpg',highlighted:false},
{id:'liam',name:'Liam O’Connor',year:'2010',city:'Sydney, Australia',region:'Asia Pacific',industry:'Operations',role:'Operations Director',employer:'Pacific Logistics',lat:-33.87,lng:151.21,tags:['Operations','Leadership'],quote:'Purpose keeps teams moving forward.',photo:'assets/profiles/liam.jpg',highlighted:false}
];
const continents=[['NORTH AMERICA',44,-103],['SOUTH AMERICA',-18,-59],['EUROPE',51,18],['AFRICA',3,21],['ASIA',39,99],['AUSTRALIA',-26,134]];
const map=L.map('map',{zoomControl:false,worldCopyJump:true,minZoom:2,zoomSnap:.25}).setView([17,5],2.15);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
continents.forEach(([name,lat,lng])=>L.marker([lat,lng],{interactive:false,icon:L.divIcon({className:'continent-label',html:name,iconSize:[150,24],iconAnchor:[75,12]})}).addTo(map));
const markerLayer=L.layerGroup().addTo(map),markerRecords=[];function profileIcon(a){const size=a.highlighted?16:12;return L.divIcon({className:'',html:`<span style="display:block;width:${size}px;height:${size}px;background:#f7bd2d;border:2px solid #fff1b6;border-radius:50%;box-shadow:0 0 12px #ffd33d"></span>`,iconSize:[size,size],iconAnchor:[size/2,size/2]})}
alumni.forEach(a=>{const marker=L.marker([a.lat,a.lng],{icon:profileIcon(a),alt:`${a.name}, ${a.city}`}).bindTooltip(`${a.name} · ${a.industry}`,{direction:'top'}).on('click',()=>selectProfile(a,true));marker.addTo(markerLayer);markerRecords.push({a,marker})});
[[39,-98,'12.4K'],[50,10,'4.7K'],[34,110,'1.9K'],[-7,23,'610'],[-24,135,'430'],[-18,-61,'320']].forEach(([lat,lng,count])=>L.marker([lat,lng],{interactive:false,icon:L.divIcon({className:'',html:`<span style="display:grid;place-items:center;width:45px;height:45px;border-radius:50%;background:#08734e;color:#fff;border:2px solid #f7bd2d;font:700 12px Inter;box-shadow:0 0 17px #001">${count}</span>`,iconSize:[45,45],iconAnchor:[22,22]})}).addTo(map));
const searchInput=document.getElementById('searchInput'),industryFilter=document.getElementById('industryFilter'),yearFilter=document.getElementById('yearFilter'),regionFilter=document.getElementById('regionFilter'),selectedProfile=document.getElementById('selectedProfile'),featuredTrack=document.getElementById('featuredTrack'),resultCount=document.getElementById('resultCount');
const unique=k=>[...new Set(alumni.map(a=>a[k]))].sort();unique('industry').forEach(v=>industryFilter.add(new Option(v,v)));unique('year').forEach(v=>yearFilter.add(new Option(v,v)));unique('region').forEach(v=>regionFilter.add(new Option(v,v)));
function selectProfile(a,move){selectedProfile.className=`selected-profile ${a.highlighted?'highlighted':''}`;selectedProfile.innerHTML=`${a.highlighted?'<span class="highlight-badge">★ HIGHLIGHTED PROFILE</span>':''}<div class="profile-head"><img class="profile-photo" src="${a.photo}" alt="Fictional portrait for ${a.name}"><div><h3>${a.name} ’${a.year.slice(-2)}</h3><p>${a.city}<br><strong>${a.role}</strong><br>${a.employer}</p><a class="profile-link" href="#">View profile ↗</a></div></div><p class="quote">“${a.quote}”</p><div class="profile-tags">${a.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="connect-button">Connect with ${a.name.split(' ')[0]}</button>`;selectedProfile.querySelector('.profile-link').onclick=e=>{e.preventDefault();alert('Demonstration profile only.')};selectedProfile.querySelector('.connect-button').onclick=()=>alert('Connection workflow placeholder.');if(move)map.flyTo([a.lat,a.lng],4.75,{duration:.8})}
function renderFeatured(records){featuredTrack.innerHTML=records.map(a=>`<article class="featured-card ${a.highlighted?'highlighted':''}" data-id="${a.id}" tabindex="0"><img src="${a.photo}" alt="Fictional portrait for ${a.name}"><div class="featured-copy">${a.highlighted?'<span class="featured-label">★ HIGHLIGHTED</span>':''}<h3>${a.name} ’${a.year.slice(-2)}</h3><p>${a.city}<br>${a.role}<br>${a.employer}</p><a href="#">View profile ↗</a></div></article>`).join('');featuredTrack.querySelectorAll('.featured-card').forEach(card=>{const activate=()=>{const a=alumni.find(x=>x.id===card.dataset.id);selectProfile(a,true);document.getElementById('mapArea').scrollIntoView({behavior:'smooth'})};card.onclick=e=>{if(e.target.tagName==='A')e.preventDefault();activate()};card.onkeydown=e=>{if(e.key==='Enter')activate()}})}
function matches(){const q=searchInput.value.trim().toLowerCase();return alumni.filter(a=>{const text=[a.name,a.city,a.region,a.industry,a.role,a.employer].join(' ').toLowerCase();return(!q||text.includes(q))&&(industryFilter.value==='all'||a.industry===industryFilter.value)&&(yearFilter.value==='all'||a.year===yearFilter.value)&&(regionFilter.value==='all'||a.region===regionFilter.value)})}
function applyFilters(){const records=matches();markerLayer.clearLayers();markerRecords.forEach(({a,marker})=>{if(records.includes(a))marker.addTo(markerLayer)});resultCount.textContent=`${records.length} profile${records.length===1?'':'s'} shown`;renderFeatured(records);if(records.length===1){selectProfile(records[0],false);map.flyTo([records[0].lat,records[0].lng],5,{duration:.75})}else if(records.length>1){map.fitBounds(L.latLngBounds(records.map(a=>[a.lat,a.lng])),{padding:[60,60],maxZoom:4.25,animate:true})}else{selectedProfile.className='selected-profile';selectedProfile.innerHTML='<h3>No profiles found</h3><p>Reset the filters to see the demonstration profiles.</p>';map.setView([17,5],2.15)}}
[searchInput,industryFilter,yearFilter,regionFilter].forEach(el=>el.addEventListener(el===searchInput?'input':'change',applyFilters));document.getElementById('resetButton').onclick=()=>{searchInput.value='';industryFilter.value=yearFilter.value=regionFilter.value='all';applyFilters();map.setView([17,5],2.15);selectProfile(alumni[0],false)};document.getElementById('viewAllButton').onclick=()=>{searchInput.value='';industryFilter.value=yearFilter.value=regionFilter.value='all';applyFilters()};document.getElementById('previousButton').onclick=()=>featuredTrack.scrollBy({left:-350,behavior:'smooth'});document.getElementById('nextButton').onclick=()=>featuredTrack.scrollBy({left:350,behavior:'smooth'});
selectProfile(alumni[0],false);renderFeatured(alumni);
const dialog=document.getElementById('joinDialog');document.getElementById('joinButton').onclick=()=>dialog.showModal();document.getElementById('closeDialog').onclick=()=>dialog.close();document.querySelectorAll('.form-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.form-tab,.form-pane').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.pane).classList.add('active')});document.getElementById('joinForm').onsubmit=e=>{e.preventDefault();alert('Submitted for authorization review. Nothing has been published.');dialog.close()};
